version: '3'
services:

  mariadb:
    build: requirements/mariadb/ #location of docker file
    container_name: mariadb #useful for finding it
    ports:
      - "3306:3306" #ports redirection : set to be the same
    volumes:
      - mariadb_data:/var/lib/mysql" #volume location
    networks:
      - docker-network #name of the nework to use for sharing data with other containers
    restart: always #restarting in case of crash
    environment: #environement variables
      MARIADB_ROOT_PASSWORD:   ${MARIADB_ROOT_PASSWORD}
      MARIADB_DB_NAME: ${MARIADB_DB_NAME}
      MARIADB_USER_NAME:  ${MARIADB_USER_NAME}
      MARIADB_USER_PASSWORD:  ${MARIADB_USER_PASSWORD}

  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "wordpress_data:/var/www/html"
    depends_on:
      - wordpress
    networks:
      - docker-network
    restart: always

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    ports:
      - "9000:9000"
    volumes:
      - "wordpress_data:/var/www/html"
    depends_on:
      - mariadb
    networks:
      - docker-network
    restart: always
    environment:
      MARIADB_MYSQL_HOST:       ${MARIADB_MYSQL_HOST}
      MARIADB_DB_NAME:          ${MARIADB_DB_NAME}
      MARIADB_USER_NAME:        ${MARIADB_USER_NAME}
      MARIADB_USER_PASSWORD:    ${MARIADB_USER_PASSWORD}
      DOMAIN_NAME:              ${DOMAIN_NAME}
      WORDPRESS_WEBSITE_TITLE:  ${WORDPRESS_WEBSITE_TITLE}
      WORDPRESS_ADMIN_NAME:     ${WORDPRESS_ADMIN_NAME}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL:    ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_USER_NAME:      ${WORDPRESS_USER_NAME}
      WORDPRESS_USER_PASSWORD:  ${WORDPRESS_USER_PASSWORD}
      WORDPRESS_USER_EMAIL:     ${WORDPRESS_USER_EMAIL}

networks:
  docker-network:

volumes:
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: bind
      device: /home/sameye/data/wordpress

  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: bind
      device: /home/sameye/data/mariadb